version: '3.1'
services:
  project-test:
  build:
    context: .
    dockerfile: Dockerfile
  container_name: project-test
  image: project-test
  restart: always
  volumes:
    - .:/project-test
  ports:
    - '8080:8080'
